name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build docker Image
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }} ghcr.io
          docker build -t ghcr.io/${{ secrets.DOCKER_HUB_USERNAME }}/item-app:v1 .
          docker push ghcr.io/${{ secrets.DOCKER_HUB_USERNAME }}/item-app:v1